<?php
// Isolated contract checks: no WordPress database, SMTP connection or customer email.
error_reporting(E_ALL);
set_error_handler(function($severity,$message,$file,$line){throw new ErrorException($message,0,$severity,$file,$line);});
$options = ['ctcl_currency'=>'USD','ctcl_smtp_authentication'=>'false','ctcl_smtp_host'=>'smtp.example.com','ctcl_smtp_port'=>587,'ctcl_smtp_username'=>'user','ctcl_smtp_password'=>'sample','ctcl_smtp_encryption'=>'tls','ctcl_smtp_from_email'=>'store@example.com','ctcl_smtp_from_name'=>'Sender name','ctcl_email_subject'=>'Order'];
function __($v,$d=null){return $v;} function esc_html($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');} function esc_attr($v){return esc_html($v);} function esc_html__($v,$d=null){return esc_html($v);} function esc_url($v){return esc_attr($v);} function get_option($v){global $options;return $options[$v]??'';} function get_bloginfo($v){return $v==='language'?'en':'Example & Store';} function home_url($v){return 'https://store.example/';} function is_rtl(){return false;} function number_format_i18n($v,$d){return number_format($v,$d);} function wp_unslash($v){return is_array($v)?array_map('wp_unslash',$v):(is_string($v)?stripslashes($v):$v);} function wp_kses_post($v){return strip_tags($v,'<p><strong><br>');} function sanitize_email($v){return $v;} function sanitize_text_field($v){return strip_tags($v);} function do_action($a,$v){} function apply_filters($a,$v){if($a==='ctcl_payment_options'||$a==='ctcl_shipping_option_display')return [['id'=>'test','name'=>'Test']];return strpos($a,'ctcl_process_payment_')===0 ? array_merge($v,['charge_result'=>true]) : $v;}
function has_filter($name){return true;}
function is_wp_error($v){return $v instanceof WP_Error;}
class WP_Error {function __construct($code,$message){}function get_error_message(){return 'Invalid cart';}}
function wp_json_encode($v){return json_encode($v);}
function get_post($id){return (object)['post_status'=>'publish','post_password'=>'','post_content'=>'product'];}
function parse_blocks($s){return [['blockName'=>'ctc-lite/ctc-lite-product-block','attrs'=>['productName'=>'Shoe <img src=x>','productPrice'=>'50.00','shippingCost'=>'5.00','variation2'=>[['value'=>'Black~image'],['value'=>'White~image']]],'innerBlocks'=>[]]];}
$options['ctcl_tax_rate']=5;
$mailResult=false;function wp_mail($to,$subject,$body,$headers){global $mailResult;return $mailResult;}
require __DIR__.'/../classes/ctcl-html.php';require __DIR__.'/../classes/ctcl-processing.php';
function check($value,$name){if(!$value)throw new Exception('FAIL: '.$name);echo "PASS: $name\n";}
class FakeMailer {public $Host,$SMTPAuth,$Port,$Username,$Password,$SMTPSecure,$From,$FromName,$SMTPDebug;function isSMTP(){}function IsHTML($v){}function smtpConnect(){throw new Exception('Premature connection');}}
$p=new ctclProcessing();$mail=new FakeMailer();$p->smtpEmailSetting($mail);check($mail->SMTPAuth===false,'false authentication setting is boolean false');$options['ctcl_smtp_authentication']='true';$p->smtpEmailSetting($mail);check($mail->SMTPAuth===true && $mail->Host==='smtp.example.com' && $mail->Port===587,'SMTP configuration completes without connecting');
$data=['order_id'=>1234,'ctcl-co-first-name'=>'Alex <script>','ctcl-co-last-name'=>'Smith','products'=>[json_encode(['itemName'=>'Shoe <img src=x>','vari'=>'N/A,Black','quantity'=>2,'itemTotal'=>100,'postId'=>8])],'items-total'=>100,'tax-total'=>5,'shipping-total'=>10,'sub-total'=>115];
$html=(new ctclHtml())->createEmailBody($data);check(strpos($html,'Example &amp; Store')!==false && strpos($html,'Sender name')===false,'email branding comes from site title');check(strpos($html,'&lt;script&gt;')!==false && strpos($html,'<img src=x>')===false,'customer and product text escaped');check(strpos($html,'USD 115.00')!==false && strpos($html,'Quantity: 2')!==false,'order totals and quantities rendered');check(strpos($html,'N/A')===false,'unused variation hidden');
class ProcessingHarness extends ctclProcessing {public $stored=0;function enterDataToTable($data){$this->stored++;}}
$_POST=array_merge($data,['products'=>array_map('addslashes',$data['products'])],['payment_option'=>'test','shipping_option'=>'test','checkout-email-address'=>'sample@example.com','checkout-special-instruction'=>'']);$p=new ProcessingHarness();$result=$p->orderProcessingShortCode();check($p->stored===1 && strpos($result,'could not be sent')!==false && strpos($result,'ctcl-order-sucesfully-placed')!==false,'email failure preserves completed order and confirmation marker');$mailResult=true;check($p->sendConfirmationEmail('x','y','z',true)===true,'email success returns boolean for checkout');check(is_string($p->sendConfirmationEmail('x','y','z')),'test-email status API preserved');
