const {test} = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const {JSDOM} = require('jsdom');
const source = fs.readFileSync('js/ctcl-frontend.js','utf8').replace(/window\.addEventListener\('DOMContentLoaded',[\s\S]*$/, 'window.CtclMain = ctclMain;');
const params={taxRate:5,currency:'USD',itemHead:'Item',varHead:'Variation',priceHead:'Price',qtyHead:'Qty',itemTotalHead:'Item total',removeItem:'Remove',itemsTotal:'Subtotal',taxTotal:'Tax',totalShipping:'Shipping',subTotal:'Total',discountTotal:'Discount',invalidCoupon:'Invalid coupon'};
function setup(html){const dom=new JSDOM(html,{url:'https://store.example/',runScripts:'outside-only'});dom.window.ctclParams=params;dom.window.eval(source);return {window:dom.window,document:dom.window.document,app:Object.create(dom.window.CtclMain.prototype)};}
const product=(name='Shoe')=>`<div class="wp-block-ctc-lite-display-column"><div class="ctclig-main-image"></div><div class="ctcl-product-container"><div><select class="ctcl-Variation-2" id="ctcl-Variation-2"><option value="White~https://store.example/ctclite-default.png">White</option><option value="Black~https://store.example/black.jpg">Black</option></select></div><div class="ctcl-quantity"><span class="ctcl-minus-qty">-</span><input class="ctcl-qty" value="1"><span class="ctcl-plus-qty">+</span></div><button class="ctcl-add-cart" data-name="${name}" data-price="50" data-qty="1" data-pic="https://store.example/base.jpg" data-post-id="8" data-shipping-cost="5">Add</button></div></div>`;
const cart=()=>`<div class="ctcl-checkout"><form id="ctcl-checkout-from"><div class="ctcl-product-list"><h5 class="ctcl-product-list-header">Products</h5><div id="ctcl-checkout-product-list"><p class="ctcl-product-loading">Loading</p><p class="ctcl-product-list-content" style="display:none">Empty</p></div><div class="ctcl-coupon-code-container"><input id="ctcl-coupon-code"><button type="button" class="ctcl-apply-cuopon-code" data-coupon='{"code":"SAVE","amount":10}'>Apply</button></div><button type="button" class="ctcl-checkout-next">Next</button></div><div class="ctcl-multip-contact" style="display:none"><button type="button" class="ctcl-checkout-back">Back</button></div></form></div>`;
const item={name:'Shoe',price:'50',qty:'2',pic:'https://store.example/black.jpg',postId:'8',shippingCost:'5',varOne:'Medium',varTwo:'Black'};
test('variation placeholder preserves base image and custom image stays scoped',()=>{const {window:w,document:d,app}=setup(product()+product('Other'));app.onVariationTwoSelect();const selects=d.querySelectorAll('select');selects[0].value='Black~https://store.example/black.jpg';selects[0].dispatchEvent(new w.Event('change'));assert.match(d.querySelector('.ctcl-add-cart').dataset.pic,/black.jpg/);assert.match(d.querySelectorAll('.ctcl-add-cart')[1].dataset.pic,/base.jpg/);selects[0].selectedIndex=0;selects[0].dispatchEvent(new w.Event('change'));assert.match(d.querySelector('.ctcl-add-cart').dataset.pic,/base.jpg/);});
test('add to cart stores product image, variations and quantity',()=>{const {window:w,document:d,app}=setup(product());app.onVariationTwoSelect();app.addItemToCart();app.increaseItemQty();app.reduceItemQyty();d.querySelector('.ctcl-plus-qty').click();d.querySelector('.ctcl-add-cart').click();const saved=JSON.parse(w.localStorage.getItem('ctclHiddenCart'))[0];assert.equal(saved.qty,'2');assert.equal(saved.varTwo,'White');assert.match(saved.pic,/base.jpg/);d.querySelector('.ctcl-minus-qty').click();d.querySelector('.ctcl-minus-qty').click();assert.equal(d.querySelector('.ctcl-qty').value,'1');});
test('cart renders image, localized mobile labels and correct totals',()=>{const {window:w,document:d,app}=setup(cart());w.localStorage.setItem('ctclHiddenCart',JSON.stringify([item]));app.loadCartItems();assert.equal(d.querySelector('.ctcl-checkout-item img').src,item.pic);assert.equal(d.querySelector('.ctcl-checkout-item-price').dataset.label,'Price');assert.equal(d.querySelector('#ctcl-subtotal-hidden-input').value,'115.00');});
test('coupon and pickup recalculate totals',()=>{const {window:w,document:d,app}=setup(cart());w.localStorage.setItem('ctclHiddenCart',JSON.stringify([item]));app.loadCartItems();app.applyCoupon();d.querySelector('#ctcl-coupon-code').value='SAVE';d.querySelector('.ctcl-apply-cuopon-code').click();assert.equal(d.querySelector('#ctcl-subtotal-hidden-input').value,'105.00');app.loadCartItems(0);assert.equal(d.querySelector('#ctcl-subtotal-hidden-input').value,'95.00');});
test('checkout navigation and empty cart state',()=>{const {document:d,app}=setup(cart());app.loadCartItems();assert.equal(d.querySelector('.ctcl-checkout-next').style.display,'none');assert.equal(d.querySelector('.ctcl-product-list-content').style.display,'');app.showHideMultipartForm();d.querySelector('.ctcl-checkout-next').click();assert.equal(d.querySelector('.ctcl-multip-contact').style.display,'');d.querySelector('.ctcl-checkout-back').click();assert.equal(d.querySelector('.ctcl-multip-contact').style.display,'none');});
test('gallery reads saved dimensions before responsive CSS and initializes each instance',()=>{const {window:w,document:d}=setup('<div class="ctcl-image-gallery" style="width:390px;height:414px;padding:10px;border:1px solid"></div><div class="ctcl-image-gallery" style="width:250px;height:300px"></div>');w.eval(fs.readFileSync('js/ctcl-image-gallery.js','utf8')+'\nwindow.Gallery=ctclImgGal;');new w.Gallery('.ctcl-image-gallery');assert.equal(d.querySelector('.ctcl-image-gallery').style.getPropertyValue('--ctcl-gallery-ratio'),'368 / 414');assert.equal(d.querySelectorAll('.ctclig-main-image').length,2);});
function blockRegistry(source){const dom=new JSDOM('',{runScripts:'outside-only',url:'https://store.example/'});const w=dom.window,blocks={};w.React={useState:v=>[typeof v==='function'?v():v,()=>{}],useEffect:()=>{}};const el=(type,props,...children)=>typeof type==='function'?type({...props,children}):({type,props:props||{},children});w.wp={components:new Proxy({}, {get:(_,key)=>key}),blockEditor:{InspectorControls:'InspectorControls',MediaUpload:'MediaUpload',InnerBlocks:'InnerBlocks',useBlockProps:()=>({})},editPost:{},i18n:{__:s=>s},element:{createElement:el},blocks:{registerBlockType:(name,definition)=>blocks[name]=definition,getCategories:()=>[],setCategories:()=>{}},data:{select:()=>({getCurrentPostId:()=>8})}};w.ctcLiteParams={currency:'USD',defaultPic:'default.png'};w.eval(source);return blocks;}
function defaults(block){return Object.fromEntries(Object.entries(block.attributes||{}).map(([k,v])=>[k,v.default]));}
test('saved product, gallery and cart markup remain compatible with original blocks',()=>{const {execFileSync}=require('node:child_process');const original=blockRegistry(execFileSync('git',['show','b6668c6:js/ctcl-block.js'],{encoding:'utf8'}));const current=blockRegistry(fs.readFileSync('js/ctcl-block.js','utf8'));for(const name of ['ctc-lite/ctc-lite-product-block','ctc-lite/ctcl-image-gallery','ctc-lite/ctc-lite-checkout-block']){const attributes=defaults(original[name]);assert.equal(JSON.stringify(current[name].save({attributes})),JSON.stringify(original[name].save({attributes})),name);}});
test('gallery editor width and aspect ratio follow attributes without gallery library',()=>{const blocks=blockRegistry(fs.readFileSync('js/ctcl-block.js','utf8'));const block=blocks['ctc-lite/ctcl-image-gallery'];const attributes={...defaults(block),mainImgWd:500,mainImgHt:350,galItems:[{id:1,url:'one.jpg'}]};const output=block.edit({attributes,setAttributes:()=>{},clientId:'example'});assert.equal(output.children[0].props.style.width,'500px');assert.equal(output.children[0].props.style['--ctcl-gallery-ratio'],'478 / 350');attributes.mainImgWd=300;assert.equal(block.edit({attributes,setAttributes:()=>{},clientId:'example'}).children[0].props.style.width,'300px');});
